POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "The patt",
  "author": "Rachel Can",
  "url": "https://patts.com/",
  "likes": 3
}


###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "karkij",
  "name": "Janne krki",
  "password": "salasana123"
}
